env:
  DOCKER_IMAGE: "gcr.io/opensourcecoin/radicle-surf-build@sha256:24252f659024808246d8c4d674f19d8d923688cd5f857f4a607fe8dbf42c491c"
  DOCKER_FILE: .buildkite/docker/rust/Dockerfile

steps:
- label: "Build, lint, test"
  commands:
  - "ci/run"
  agents:
    production: "true"
    platform: "linux"
