#!/usr/bin/env bash
set -eou pipefail

echo '--- Formatting'
cargo fmt -- --check

echo '--- Clippy'
cargo clippy --all-targets --all-features -- -D warnings

if [[ "${CI:-false}" = "true" ]]
then
    sed -i -e 's|db-path.*|db-path = "/cache/cargo/advisory-db"|' deny.toml
fi

echo '--- deny: Advisories'
cargo deny check advisories

echo '--- deny: Licenses'
cargo deny check licenses

echo '--- deny: Bans'
cargo deny check bans

echo '--- deny: Sources'
cargo deny check sources

echo '--- Build'
GIT_FIXTURES=1 cargo build -vv --all --features serialize

echo '--- Tests'
cargo test --all --features serialize

echo '--- Docs'
cargo doc --no-deps
